use db_autogenerated;
select postalZip as codigoPostal, region, country as pais from myTable;
select * from myTable where phone like '(811)%';
select * from myTable where country like 'Spain' or country like 'Italy';
select count(id) from myTable;
select region, country, postalZip from myTable where country like 'Germany' or country like 'Turkey';
select max(id), min(id) from myTable;
select country, count(*)  from myTable group by country;
select * from myTable order by postalZip asc limit 10;
delete from myTable where country like 'Singapure';
update myTable set country='España' where country='Spain';
select * from myTable where country like 'España';


